CBIIT/icdc-codebase

src/main/frontend/src/components/App.js
src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/components/NavBar/NavBarView.js
src/main/frontend/src/pages/cases/cases.js
src/main/frontend/src/pages/programs/programs.js

Router fixes

---

src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/components/Stats/StatsView.js
src/main/frontend/src/components/Stats/statsMockData.js

**Description**
1. Footer fixes
2. codacy fixes

Footer fixes

---

src/main/webapp/WEB-INF/index.jsp

Description:
Fixed the issue with body properties in the frontend are getting overridden

ICDC-489 Fixing the scrolll issue in all frontend pages

---

src/main/frontend/src/components/Layout/LayoutView.js

**Code changes**
1. Redirected the homepage to dashboard page

ICDC-488 Redirecting landing page to dashboard page

---

src/main/frontend/src/components/Footer/FooterView.js

**Code changes**
1. Text changes of footer 
2. The padding of NIH links

Footer padding adjustments

---

src/main/frontend/src/components/App.js
src/main/frontend/src/components/Footer/FooterView.js
src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/components/NavBar/NavBarView.js
src/main/frontend/src/components/Stats/StatsView.js
src/main/frontend/src/components/ThemeContext.js
src/main/frontend/src/components/Widgets/WidgetView.js
src/main/frontend/src/pages/programs/programs.js
src/main/frontend/src/themes/dark.js
src/main/frontend/src/themes/index.js
src/main/frontend/src/themes/light.js

**Code Changes**
1. Added a new dark theme switcher logic
2. Added theme switcher logic
3. Added the react contexts to pass the props down the line
4. Added the local storage to save the previously selected theme value.
5. Added state value to render the theme changes
6. USed react hook functions to create a state within the function.

ICDC-322 : Implement Theme Changer

---

src/main/frontend/src/components/Stats/StatsController.js
src/main/frontend/src/components/Stats/StatsView.js

**Code Changes:**
1.  modified the graphQl query to recive Aliquotts data.
2. Updated the stats view component with Aliquot data

ICDC-535 Updating Aliquots data to the stats component

---

src/main/frontend/.env
src/main/frontend/package.json
src/main/frontend/src/index.js

1. Added the default backend api url as dev.
2. During build it will be replaced with actual backend of that env.

ICDC-674: Env variable setup

---

src/main/frontend/src/pages/dashboard/caseTable/caseController.js
src/main/frontend/src/pages/dashboard/caseTable/caseView.js
src/main/frontend/src/pages/dashboard/caseTable/customFooter.js
src/main/frontend/src/pages/dashboard/dashboard.js
src/main/frontend/src/themes/light.js

**Description:
Created a new table for cases view
**

ICDC-656 Case table view

---

src/main/frontend/.env
src/main/frontend/package-lock.json
src/main/frontend/package.json
src/main/frontend/src/components/NavBar/NavBarView.js
src/main/frontend/src/components/ProfileMenu/ProfileMenuView.js
src/main/frontend/src/components/Widgets/PieCharts/BreedDonut/BreedDonut.js
src/main/frontend/src/components/Widgets/PieCharts/TumorDonut/TumorDonut.js
src/main/frontend/src/components/Widgets/WidgetView.js
src/main/frontend/src/pages/dashboard/dashboard.js
src/main/frontend/src/themes/light.js

**Code Changes:**
1. Added the fence auth calls to the backend.
2. Changed the colors of the widgets headers.
3. Added the new variables in .env for fence support.

ICDC-770 Frontend fence logic

---

src/main/frontend/src/components/NavBar/NavBarView.js

**Code Changes:**
1. Changed the Nav links to buttons.
2. Changed the router link to NavLink to get the active state

ICDC-683 Adding active style for nav buttons

---

src/main/frontend/src/components/Footer/FooterView.js
src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/pages/about/aboutView.js
src/main/frontend/src/pages/dgabPage/dgbaRoute.js

**Code Changes:**
Added new route for DGAB

Adding new route DGAB

---

src/main/frontend/src/components/SideBar/SideBarComponents/BreedsListItem.js
src/main/frontend/src/components/SideBar/SideBarComponents/DiagnosisListItem.js
src/main/frontend/src/components/SideBar/SideBarComponents/SexListItem.js
src/main/frontend/src/components/SideBar/SideBarComponents/StudyCodesListItem.js

**Changes:**
The value in 0 first list of the checkbox is getting confused with binary 0. Chnaged

Removing first checkbox in sidebar

---

src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/components/NavBar/NavBarView.js
src/main/frontend/src/pages/about/aboutView.js
src/main/frontend/src/pages/bpsc/bpscRoute.js
src/main/frontend/src/pages/bpsc/bpscView.js
src/main/frontend/src/pages/programs/components/programcard.js

**Changes:**
1. Added new route for bpsc page.
2. Changed the program card missing data.
3. Added BPSC page.

ICDC-860 Adding bpsc page and changing hamburger icon

---

src/main/frontend/src/components/Footer/FooterView.js
src/main/frontend/src/pages/bpsc/bpscView.js
src/main/frontend/src/pages/dgabPage/dgabPageView.js

**Changes:**
1. Adding space after the colon.
2. Changing footer links.

small fixes on BPSC page

---

src/main/frontend/src/components/ThemeContext.js
src/main/frontend/src/pages/dashboard/caseTable/caseView.js
src/main/frontend/src/themes/dark.js
src/main/frontend/src/themes/light.js

**Changes:** 
1. Removing delete button from MUI DataTable
2. Removing double declaration of store and provider

ICDC-865 Removing delete button from Data Table

---

src/main/frontend/src/components/Header/HeaderView.js
src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/components/NavBar/NavBarView.js
src/main/frontend/src/themes/dark.js
src/main/frontend/src/themes/light.js

**Changes:**
1. Added new hannah colorguide
2. Now the logo header is fixed
3. NavBar is Fixed

Fixed header

---

src/main/frontend/src/pages/dashboard/caseTable/caseView.js
src/main/frontend/src/pages/dashboard/caseTable/customFooter.js
src/main/frontend/src/pages/studies/studiesView.js
src/main/frontend/src/themes/dark.js
src/main/frontend/src/themes/light.js

Not using the theme may cause an issue.  Need to update it after theme has been done.

Update style of data table in the dashboard. 

---

src/main/frontend/src/components/Layout/LayoutContainer.js
src/main/frontend/src/components/Layout/LayoutView.js
src/main/frontend/src/components/NavBar/NavBarView.js
src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
src/main/frontend/src/pages/dashboard/dashboard.js
src/main/frontend/src/pages/dashboard/dashboardController.js

fix sidebar margin-left affects other pages.

fix sidebar margin left affects other pages.

---

src/main/frontend/src/components/Widgets/PieCharts/CustomActiveDonut/CustomActiveDonutController.js
src/main/frontend/src/components/Widgets/PieCharts/CustomActiveDonut/CustomActiveDonutView.js
src/main/frontend/src/components/Widgets/PieCharts/Donut/DonutView.js
src/main/frontend/src/components/Widgets/WidgetView.js
src/main/frontend/src/pages/dashboard/dashboard.js
src/main/frontend/src/themes/dark.js
src/main/frontend/src/themes/light.js

**Changes:**
Added new custom pie charts.
Changed the background and text colors.
**Pending:**
Style Changes

ICDC-925 Adding the custom pies

---

src/main/frontend/src/components/Widgets/WidgetView.js
src/main/frontend/src/pages/dashboard/dashboard.js
src/main/frontend/src/pages/programDetail/components/programDetailView.js

**Changes:**
1. Added logic to get new lines after ** in program detail page
2. Changed the background widget on passing params

program detail summary fix and widget color fix

---

src/main/frontend/src/pages/about/steeringCommitteeView.js
src/main/frontend/src/pages/about/submitDataView.js
src/main/frontend/src/pages/landing/landingController.js

Update landing animation loop count to infinite
Update table content in steeringCommittee。
Update down pdf link，review in-browser pdf reader instead of downloading it

Changes required from matt

---

src/main/frontend/src/pages/caseDetail/caseDetailView.js

Fixed issue in Case detail,  when user clicks on sort ( on an column )  the label Moves.

---

src/main/frontend/src/components/NavBar/NavBarView.js

Adjusted the menu items to be center aligned in the main nav bar. Applied absolute positioning for my cart and filter icons.

Menu items to be center aligned

---

src/main/frontend/src/components/FileGrid/FileGridView.js

Changed default sort in ascending order of File Name column for study detail page.

---

src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js

Issue was created due to unsafe if condition on Sunburst chart. When caseSize is set 0, react was crashing.

1410 - Fixed app crashing issue. 

---

src/main/frontend/src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js

Fixed: Title should not be shown in sunburst if mouse hovered element is not in filtered data.

---

src/main/frontend/src/pages/cart/cartView.js
src/main/frontend/src/pages/dashboard/components/tabConfigs/caseConfig.js
src/main/frontend/src/pages/dashboard/components/tabConfigs/fileConfig.js
src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
src/main/frontend/src/pages/dashboard/components/tabController.js
src/main/frontend/src/pages/dashboard/components/tabView.js
src/main/frontend/src/pages/dashboard/store/dashboardAction.js
src/main/frontend/src/pages/dashboard/store/dashboardReducer.js
src/main/frontend/src/utils/graphqlQueries.js

Update Cart deletion function & add cart supervision

Update Cart deletion function & add cart supervision

---

src/main/frontend/src/pages/dashboard/components/tabConfigs/fileConfig.js
src/main/frontend/src/pages/dashboard/components/tabConfigs/sampleConfig.js
src/main/frontend/src/pages/dashboard/components/tabController.js
src/main/frontend/src/utils/dashboardUtilFunctions.js

fix Counts reported by the statistics bar do not fully align with counts reported via dashboard tabs

fix Counts reported by the statistics bar do not fully align with counts reported via dashboard tabs

---

src/main/frontend/src/pages/programDetail/components/programDetailView.js
src/main/frontend/src/pages/programs/components/programcard.js
src/main/frontend/src/themes/dark.js
src/main/frontend/src/themes/light.js

1) Tighten up spacing in programDetails page.
2) Fixed the text is colliding with the button for CMCP on the programs page

Minor UI Improvements  - Programs Spacing

---

src/main/frontend/src/components/SideBar/SideBarComponents/FacetFilters.js
src/main/frontend/src/utils/googleAnalytics/index.js

- Tracking Group & Panel's 'expand' & 'collapse'
- Tracking filtering events based on Group Dimension(aka Panel) gets filterd.

Added GA Event Tracking for Facets
